---
# Debian related OS tasks

- name: apt dist-upgrade
  apt:
    upgrade: dist
    autoremove: true

- name: install additional packages
  apt:
    name:
      - zip
      - unzip
      - bzip2
      - screen
      - curl
      - software-properties-common
      - apt-transport-https
      - facter
      - python3-passlib
      - python3-bcrypt
    state: latest
