---
# Ubuntu related OS tasks

- name: apt dist-upgrade
  apt:
    upgrade: dist
    autoremove: true

- name: install additional packages
  apt:
    name:
      - zip
      - unzip
      - bzip2
      - screen
      - curl
      - language-pack-en-base
      - software-properties-common
      - facter
      - unattended-upgrades
      - gnupg2
      - python-passlib
      - python-bcrypt
    state: latest
