---
# Amazon Linux related docker OS tasks

- name: install python docker via pip
  pip:
    name: docker
    executable: pip3
    state: latest

- name: install docker
  yum: 
    name: 
      - docker
    state: latest
  vars:
    ansible_python_interpreter: python2
