---
# Amazon Linux related docker OS tasks

- name: install python docker via pip
  pip:
    name: docker
    state: latest

- name: install docker
  yum: 
    name: 
      - docker
    state: latest
