---
# vars file for docker_container

nextcloud_traefik_label:
  nginx:
    traefik.enable:                        "false"
    com.centurylinklabs.watchtower.enable: "true"
  apache:
    traefik.docker.network: "frontend"
    traefik.enable:         "true"
    traefik.frontend.rule:  "Host:{{ nextcloud_server_fqdn }}"
    traefik.port:           "80"
    traefik.protocol:       "http"
    traefik.frontend.headers.referrerPolicy:          "no-referrer"
    traefik.frontend.headers.SSLRedirect:             "true"
    traefik.frontend.headers.STSSeconds:              "315360000"
    traefik.frontend.headers.browserXSSFilter:        "true"
    traefik.frontend.headers.contentTypeNosniff:      "true"
    traefik.frontend.headers.forceSTSHeader:          "true"
    traefik.frontend.headers.STSIncludeSubdomains:    "true"
    traefik.frontend.headers.STSPreload:              "true"
    traefik.frontend.headers.customFrameOptionsValue: "SAMEORIGIN"
    com.centurylinklabs.watchtower.enable:            "true"

nextcloud_db_links:
  pgsql:
    - 'nextcloud-db:db'
    - 'redis:redis'
  mysql:
    - 'nextcloud-db:db'
    - 'redis:redis'
  sqlite:
    - 'redis:redis'
